version: "3"

services:

  database:
    image: mysql:latest
    restart: always
    networks:
      - ita
    ports:
      - 3306:3306
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database-data:/var/lib/mysql
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/seed.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./database/views.sql:/docker-entrypoint-initdb.d/3.sql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./.env

  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    networks:
      - ita
    depends_on: 
      - database
    ports:
      - 3030:3030
    env_file:
      - ./api/.env

  
  application:
    build:
      context: ./application
      dockerfile: application.dockerfile
    ports:
      - 3000:3000
    networks:
      - ita
    env_file:
      - ./application/.env
    depends_on: 
      - api

networks:
  ita: {}

volumes:
  database-data: