version: "3"

services:

  database:
    image: mysql:latest
    networks:
      - abode
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database-data:/var/lib/mysql
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/seed.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./database/views.sql:/docker-entrypoint-initdb.d/3.sql"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=some_password
    env_file:
      - ./.env

  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    networks:
      - abode
    depends_on: 
      - database
    ports:
      - 3030:3030
    env_file:
      - ./api/.env

  
  application:
    build: ./application
    #   context: .
    #   dockerfile: ./application/Dockerfile
    command: npm start
    image: node:16
    ports:
      - 3000:3000
    volumes:
      - ./application:/usr/app
      - /usr/app/node_modules
    networks:
      - abode
    env_file:
      - ./application/.env
    depends_on: 
      - api

networks:
  abode: {}

volumes:
  database-data: