INSERT INTO products
VALUES
(
	1, 
    true, 
    true, 
    'Kelty', 
    'Rumpus', 
    JSON_ARRAY("kelty_rumpus.jpeg", "kelty_rumpus_02.jpg", "kelty_rumpus_03.jpg"),
    "/kelty-rumpus",
    299.95,
    6,
    '3-season',
    16,
    72,
    'Blue',
    4,
    JSON_ARRAY("Spacious interior perfectly suited for family camping, festival festivities, or backyard getaways", "Vestibule door converts to extra large shade awning for additional external, covered storage", "Kelty is synonymous with quality in the outdoor community. Designed in Colorado, Kelty gear is built to last"),
    JSON_ARRAY("family camping", "extra large", "easy packing and transport")
),
(
	2, 
    true, 
    true, 
    'Marmot', 
    'Limestone', 
    JSON_ARRAY("marmot_limestone.png"),
    "/kelty-rumpus",
    389.00,
    4,
    '4-season',
    10,
    58,
    'Orange',
    4,
    JSON_ARRAY("Easy-pitch construction creates vertical interior walls for extra head room","Water-resistant fabrics and full-coverage fly vents to enjoy outdoor living in comfort","Keep essentials neatly organized and within reach with numerous interior pockets"),
    JSON_ARRAY("family camping","spacious","easy-pitch design")
),
(
	3, 
    true, 
    true, 
    'The North Face', 
    'Stormbreak', 
    JSON_ARRAY("north-face_stormbreak.jpeg"),
    "/kelty-rumpus",
    185.00,
    2,
    '3-season',
    5,
    29,
    'Yellow',
    5,
    JSON_ARRAY("High-low ventilation delivers optimal airflow", "Two multi-configuration, twin-zip doors for easy access and amazing views outdoors", "Fully seam-taped canopy and floor made without flame-retardant coatings"),
    JSON_ARRAY("lightweight", "abundant headroom", "easy-pitch design")
),
(
	4, 
    true, 
    false, 
    'Kelty', 
    'Grand Mesa', 
    JSON_ARRAY("kelty_grand-mesa.jpeg"),
    "/kelty-rumpus",
    139.95,
    2,
    'Summer',
    4,
    30,
    'Grey',
    3,
    JSON_ARRAY("Lightweight aluminum poles and carry bag included make the Grand Mesa perfect for backpacking", "Affordable option that provides big value without straining your backpacking budget"),
    JSON_ARRAY("lightweight", "affordable", "easy setup")
),
(
	5, 
    true, 
    false, 
    'REI Co-op', 
    'Passage', 
    JSON_ARRAY("REI_passage.jpeg"),
    "/kelty-rumpus",
    96.95,
    1,
    '3-season',
    4,
    20,
    'Olive',
    4,
    JSON_ARRAY("Made with solution-dyed mesh to reduce water and energy use in manufacturing", "Adjustable ceiling vents help reduce condensation by moving moist air outside", "X-pole configuration makes it easy to set up and increases the vertical space at the ends of the tent"),
    JSON_ARRAY("sustainable manufactoring", "gear storage", "bad weather coverage")
),
(
	6, 
    true, 
    false, 
    'Quechua', 
    'Arpenaz', 
    JSON_ARRAY("quechua_arpenaz.jpeg"),
    "/kelty-rumpus",
    159.00,
    3,
    '3-season',
    12,
    82,
    'Olive',
    3,
    JSON_ARRAY("Lab tested protection against the elements", "Designed to be durable, Quechua offers a two-year repairs guarantee", "Includes comfort features with an awning for your shoes and a free standing dome structure that can be easily moved to find the ideal location"),
    JSON_ARRAY("Free-standing structure", "easy-pitch design", "casual camper")
),
(
	7, 
    true, 
    false, 
    'Thule', 
    'Tepui Autana', 
    JSON_ARRAY("thule_tepui_autana.jpeg"),
    "/kelty-rumpus",
    2249.99,
    3,
    '3-season',
    192,
    47,
    'Green',
    2,
    JSON_ARRAY("Welded aluminum construction is durable with a fully wrapped internal frame built to withstand any environment", " Features an extended canopy entrance with removable annex for additional privacy", "Diamond plate base provide added protection from rocks, branches and other trail debris"),
    JSON_ARRAY("Car camping", "roof tent", "sturdy and long-lasting")
),
(
	8, 
    true, 
    false, 
    'REI Co-op', 
    'Base Camp', 
    JSON_ARRAY("REI_base_camp.jpeg"),
    "/kelty-rumpus",
    449.00,
    4,
    '4-season',
    17,
    80,
    'Orange',
    3,
    JSON_ARRAY("Wide-mouth door orientation gives all sleepers equal access to the 2 doors — no need to crawl over tentmates to get in and out", "Vestibule stake-out loops large enough to accommodate skis or snowboards", "Dome architecture is designed to be highly stable and durable in all seasons while maximizing interior livability"),
    JSON_ARRAY("gear storage", "sustainable manufactoring", "ventilation")
),
(
	9, 
    true, 
    false, 
    'Eureka', 
    'Copper Canyon', 
    JSON_ARRAY("eureka_copper_canyon.jpeg"),
    "/kelty-rumpus",
    469.95,
    8,
    '3-season',
    31,
    130,
    'Grey/Blue',
    3,
    JSON_ARRAY("Near-vertical walls create lots of standing room and are ideal when camping with air mattress and cots","Cabin style model has a divider down the middle so you can easily split up the room between two families", "Zippered E! Powerport lets you easily run an extension cord inside so you can keep everyone’s gadgets charged"),
    JSON_ARRAY("cabin-style tent","smart features","casual camping")
)
;

	